id: P8A2C954A
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: it
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    1ebd76037bb341058d3d5150e84e88b2:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    0a097a6deec6497299159d3b4673d63c:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    93f33de559564d0ab11d1126f8f603e9:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    94326c4faefa4e4d93d63a8288f91f5e:
      title: Praise to Mañjughoṣa
      parent: Praise
    861ccc6971594476817c9629d43824e7:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    f1a963f62679402fb7c17214c6966e53:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    497c8f0bd0c344a6a9419cdd412e6b92:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    d5a89f59cccf474dafd67baf22470bb3:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.974851'
last_modified_at: '2022-03-01T01:55:51.974854'
